#! /bin/sh

case $# in
1) find $HOME -name $1
   exit ;;
3) if [ "$2" = "-f" ] ; then
     find $HOME -name "$1" > "$3" 2>&1
     cat "$3" | grep "$1"
     exit
   fi
   if [ "$2" = "-p" ] ; then
     find "$3" -name "$1"
     exit
   fi
   echo 'Benutzung: bsuch filename1 [-f filename2] [-p pfad]'
   exit ;;
5) if [ "$2" = "-f" -a "$4" = "-p" ] ; then
     find "$5" -name "$1" > "$3" 2>&1
     cat "$3" | grep "$1"
     exit
   fi
   if [ "$2" = "-p" -a "$4" = "-f" ] ; then
     find "$3" -name "$1" > "$5" 2>&1
     cat "$5" | grep "$1"
     exit
   fi
   echo 'Benutzung: bsuch filename1 [-f filename2] [-p pfad]'
   exit ;;
*) echo 'Benutzung: bsuch filename1 [-f filename2] [-p pfad]'
   exit ;;
esac

exit